-- ============================================================
-- رُواء — تهيئة قاعدة البيانات لاستقبال طلبات نموذج البريف
-- شغّل هذا الملف في: Supabase → SQL Editor → New query → Run
-- ============================================================

-- 1) جدول الطلبات
create table if not exists public.requests (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  name         text,
  phone        text,
  email        text,
  service_type text,
  message      text
);

-- 2) تفعيل أمان مستوى الصفوف (RLS)
alter table public.requests enable row level security;

-- 3) السماح للزوّار (anon) بإرسال طلب جديد من النموذج
drop policy if exists "anon can insert requests" on public.requests;
create policy "anon can insert requests"
  on public.requests
  for insert
  to anon
  with check (true);

-- 4) السماح بقراءة الطلبات بمفتاح anon (تستخدمه لوحة /admin)
--    ⚠️ ملاحظة أمنية: مفتاح anon عام، أي أن أي شخص يملكه يمكنه قراءة الطلبات.
--    لحماية أقوى لاحقًا: انقل قراءة اللوحة إلى مسار خادمي (Route Handler)
--    يستخدم service_role، واحذف سياسة القراءة هذه.
drop policy if exists "anon can read requests" on public.requests;
create policy "anon can read requests"
  on public.requests
  for select
  to anon
  using (true);
